version: '3.8'
services:
  npm:
    build:
      context: ./
      dockerfile: ./Dockerfile.npm
    container_name: npm
    stdin_open: true
    tty: true
    ports:
      - '5001:5001'
    volumes:
      - ./:/app
      - './logs:/app/logs:rw'
      - ./node_modules:/app/node_modules
    env_file:
      - ./.env
  prod:
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    container_name: user_service_prod
    ports:
      - '5000:5000'
    volumes:
      - './logs:/app/logs:rw'
      - './keys:/app/keys:rw'
    env_file:
      - ./.env
